#!/usr/bin/env python

from __future__ import division, absolute_import, print_function

import mediafile
import sys

field = mediafile.MediaField(
    mediafile.MP3DescStorageStyle(u'ITUNESADVISORY'),
    mediafile.MP4StorageStyle(u'rtng'),
    mediafile.StorageStyle(u'ITUNESADVISORY'),
    mediafile.ASFStorageStyle(u'ITUNESADVISORY'),
    out_type=int,
)
mediafile.MediaFile.add_field('itunesadvisory', field)

for target in sys.argv[1:]:
    mf = mediafile.MediaFile(target)
    print(mf.itunesadvisory or 0)
